# NUMPY Practice

In [2]:
import numpy as np

In [3]:
np

<module 'numpy' from 'C:\\Users\\SCS\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.full(5,3)

array([3, 3, 3, 3, 3])

In [21]:
a=np.array([1,2,3,4,5,6])
a+1
a[3]

4

In [10]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [13]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
b=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
b[2,2]=10
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [24]:
b[1,:]

array([4, 5, 6])

In [25]:
b[:,2]

array([ 3,  6, 10])

In [28]:
np.random.seed(2)
100*np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [37]:
c=np.random.randint(low=1,high=50,size=(3,3))
c

array([[35, 10, 38],
       [ 7, 23,  7],
       [20, 19,  2]])

In [32]:
b>2

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [38]:
c[c<=30]

array([10,  7, 23,  7, 20, 19,  2])

In [39]:
c.max()

38

In [40]:
c.sum()

161

In [43]:
c.mean()

17.88888888888889

In [44]:
c.std()

11.929836027972932

In [21]:
u= np.array([1,5,4,3])
v=np.array([2,3,5,2])
x=np.random.randint(low=1,high=6,size=(3,4))
x

array([[2, 2, 1, 4],
       [3, 3, 5, 1],
       [5, 2, 3, 3]])

In [22]:
u.dot(v)

43

In [25]:
def matrix_vector_multiplication(u,x):
    assert u.shape[1]==x.shape[0]
    s=u.shape[0]
    res=np.zeros(s)
    for i in range(s):
      res[i]=u[i].dot(x)
    
    return res

In [26]:
matrix_vector_multiplication(x,u)

array([28., 41., 36.])

In [28]:
x.dot(u)

array([28, 41, 36])

In [37]:
i=np.eye(4)
i

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [39]:
x.dot(i)

array([[2., 2., 1., 4.],
       [3., 3., 5., 1.],
       [5., 2., 3., 3.]])

In [50]:
vec=np.random.randint(low=1,high=6,size=(4,3))
vec
vs=vec[[0,1,2]]

In [51]:
np.linalg.inv(vs)

array([[-0.11764706, -0.02941176,  0.32352941],
       [ 0.41176471, -0.14705882, -0.38235294],
       [-0.23529412,  0.44117647,  0.14705882]])